### ISSUE TITLE
Roadmap to v0.1 release

### ISSUE THREAD

**Issue by MrPicklePinosaur** [MrPicklePinosaur/shrs#76]
List of tasks to complete before releasing early access
- [ ] source code documented
- [ ] clean up code (remove unwraps, resolve most TODOs)
- [ ] decent test suite
- [ ] contributor documentation, list of tasks to work on for contributors
- [ ] fix lot of usability bugs (cd and tab completion seems to panic a lot)

List of features to implement
- [ ] couple of plugins as example on how to write plugins
- [ ] most of POSIX
